# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/auth.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'auth/v1/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth/v1/auth.proto\x12\x07\x61uth.v1\"<\n\x17\x45xchangeIdentityRequest\x12\x12\n\ngoogle_sub\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"@\n\x18\x45xchangeIdentityResponse\x12\x0b\n\x03jwt\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpires_at_unix\x18\x02 \x01(\x03\x32\x66\n\x0b\x41uthService\x12W\n\x10\x45xchangeIdentity\x12 .auth.v1.ExchangeIdentityRequest\x1a!.auth.v1.ExchangeIdentityResponseB&Z$stock-news/auth/proto/auth/v1;authv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.v1.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$stock-news/auth/proto/auth/v1;authv1'
  _globals['_EXCHANGEIDENTITYREQUEST']._serialized_start=31
  _globals['_EXCHANGEIDENTITYREQUEST']._serialized_end=91
  _globals['_EXCHANGEIDENTITYRESPONSE']._serialized_start=93
  _globals['_EXCHANGEIDENTITYRESPONSE']._serialized_end=157
  _globals['_AUTHSERVICE']._serialized_start=159
  _globals['_AUTHSERVICE']._serialized_end=261
# @@protoc_insertion_point(module_scope)
